package com.laeben.corelauncher.minecraft.modding.curseforge;

import com.google.gson.stream.JsonReader;
import com.laeben.core.concurrency.CancellableToken;
import com.laeben.core.entity.RequestParameter;
import com.laeben.core.entity.exception.HttpException;
import com.laeben.core.entity.exception.NoConnectionException;
import com.laeben.core.entity.exception.StopException;
import com.laeben.core.event.function.ProgressFunction;
import com.laeben.core.network.Network;
import com.laeben.core.network.entity.NetworkToken;
import com.laeben.core.network.requester.RequesterFactory;
import com.laeben.core.util.StrUtil;
import com.laeben.corelauncher.api.Configurator;
import com.laeben.corelauncher.api.entity.Profile;
import com.laeben.corelauncher.minecraft.entity.Version;
import com.laeben.corelauncher.minecraft.modding.curseforge.entity.*;
import com.laeben.corelauncher.minecraft.modding.entity.*;
import com.laeben.core.entity.Path;
import com.google.gson.*;
import com.laeben.corelauncher.minecraft.modding.entity.resource.*;
import com.laeben.corelauncher.minecraft.modding.event.ModdingContext;
import com.laeben.corelauncher.ui.controller.browser.search.CurseForgeSearch;
import com.laeben.corelauncher.ui.controller.browser.search.Search;
import com.laeben.corelauncher.util.GsonUtil;

import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class CurseForge implements ModSource {

    // this key is a default approach generated by the developer
    // if you are going to fork or modify this repository, you must change this with your own
    private static final String BASE_API_KEY = "$2a$10$fdQjum78EUUUcJIw2a6gb.m1DNZCQzwvf0EBcfm.YgwIrmFX/1K3m";

    private static final String CDN_URL = "https://mediafilez.forgecdn.net/files/";
    private static final String BASE_URL = "https://api.curseforge.com";
    private static final int GAME_ID = 432;
    private static CurseForge instance;

    private final Gson gson;

    private List<CurseForgeCategory> categories;
    private final RequesterFactory factory;


    public CurseForge(){
        gson = GsonUtil.EMPTY_GSON;

        factory = new RequesterFactory(BASE_URL);

        instance = this;
    }

    public static CurseForge getForge(){
        return instance;
    }

    private String getApiKey(){
        final var storedKey = Configurator.getConfig().getCurseForgeApiKey();
        return storedKey == null ? BASE_API_KEY : storedKey;
    }

    public CurseForgeSearchResponse search(CurseForgeSearchRequest s) throws NoConnectionException, HttpException, IOException, StopException {
        var params = RequestParameter.classToParams(s, CurseForgeSearchRequest.class);
        if (s.gameVersions != null){
            var vers = params.stream().filter(x -> x.key().equals("gameVersions")).findFirst().orElse(null);
            if (vers != null){
                var value = ((List<String>)vers.value()).stream().map(a -> "\"" + a + "\"").toList();
                var param = new RequestParameter("gameVersions", value).markAsEscapable();
                params.remove(vers);
                params.add(param);
            }
        }

        String a = get("/v1/mods/search", params);
        return gson.fromJson(a, CurseForgeSearchResponse.class);
    }

    /**
     * Retrieve resources from CurseForge API.
     * @param opt options for handled ids, nullable
     */
    public List<CurseForgeResource> getResources(List<Object> ids, Options opt) throws NoConnectionException, StopException, IOException {
        if (ids.isEmpty())
            return null;
        var request = new ModsRequest();
        request.modIds = (opt == null ? ids.stream() : opt.streamIdList(ids)).map(a -> a instanceof Double da ? da.intValue() : (int)a).toArray(Integer[]::new);
        String json = gson.toJson(request);
        var f = post("/v1/mods", json);
        if (f == null)
            return null;
        var data = gson.fromJson(f, JsonObject.class).get("data").getAsJsonArray();

        return data.asList().stream().map(a -> gson.fromJson(a, CurseForgeResource.class)).toList();
    }
    public Manifest getModpackManifest(Modpack mp) throws NoConnectionException, HttpException, IOException, StopException {
        if (mp.fileId == null) return null;

        String idf = mp.fileId.toString();
        if (idf.length() > 4 && idf.length() < 8) { // -- ideally 7 digits --
            idf = idf.substring(0, 4) + "/" + idf.substring(4);
        }
        //else doesn't know what's going to happen

        final String manifestUrl = CDN_URL + idf + "/manifest.json";
        //final String manifestUrl = mp.fileUrl.substring(0, mp.fileUrl.lastIndexOf('/')) + "/manifest.json";
        var temp = Network.download(NetworkToken.create(manifestUrl, Configurator.getConfig().getTemporaryFolder().to("manifest-" + mp.fileHash + ".json"), false));
        return gson.fromJson(new JsonReader(new FileReader(temp.toFile())), Manifest.class);
    }
    public void fillResource(CurseForgeResource r, Options opt) throws NoConnectionException, HttpException, IOException, StopException {
        var params = new ArrayList<RequestParameter>();

        // curse forge does not support multiple file searching

        if (opt.hasGameVersion())
            params.add(new RequestParameter("gameVersion", opt.getVersionIds().size() == 1 ? opt.getVersionId() : opt.getVersionIds().stream().max(Version.VersionIdComparator.INSTANCE).get()));
        if (opt.hasLoaderType())
            params.add(new RequestParameter("modLoaderType",  opt.getLoaders().size() == 1 ? opt.getLoaderType().getIdentifier() : opt.getLoaders().get(0)));

        String g = get("/v1/mods/" + r.id + "/files", params);
        var rs = gson.fromJson(g, JsonObject.class);
        r.latestFiles = rs.get("data").getAsJsonArray().asList().stream().map(x -> gson.fromJson(x, CurseForgeFile.class)).toList();
    }

    public List<CurseForgeFile> getFiles(List<Integer> ids) throws NoConnectionException, StopException, IOException {
        var obj = new JsonObject();
        var arr = new JsonArray();
        arr.asList().addAll(ids.stream().map(JsonPrimitive::new).toList());
        obj.add("fileIds", arr);
        String pst = gson.toJson(obj);
        String ans = post("/v1/mods/files", pst);
        var abc = gson.fromJson(ans, JsonObject.class).get("data").getAsJsonArray().asList().stream().map(x -> gson.fromJson(x, CurseForgeFile.class));
        return abc.distinct().toList();
    }

    @Override
    public Path extractModpack(Modpack mp, Path path, boolean overwriteManifest, ProgressFunction onProgress, CancellableToken<?> token) throws StopException, NoConnectionException, HttpException, IOException {
        var zip = path.to("mpInfo.zip");
        String name = StrUtil.pure(mp.name);
        var tempDir = path.to(name);
        var manifest = path.to("manifest-" + name + ".json");
        if (overwriteManifest)
            manifest.delete();
        if (!manifest.exists()){
            Path ppp = null;
            try{
                ppp = Network.download(NetworkToken.create(mp.fileUrl, zip, false).withLogging(onProgress).syncWith(token));
                //Modder.getModder().getHandler().execute(new KeyEvent("stop"));
                onProgress.onContext(ModdingContext.EXTRACTING_MODPACK);
                zip.extract(tempDir, null);
                tempDir.to("manifest.json").move(manifest);
                tempDir.to("overrides").move(path);
            }
            finally {
                if (ppp != null) ppp.delete();
                tempDir.delete();
            }
        }

        return manifest;
    }

    private String get(String api, List<RequestParameter> params) throws NoConnectionException, HttpException, IOException, StopException {
        var r = factory.create().to(api)
                .withHeader(new RequestParameter("x-api-key", getApiKey()))
                .withParam(new RequestParameter("gameId", GAME_ID));
        if (params != null)
            r.withParams(params);
        return r.getString();
    }
    private String post(String api, String body) throws NoConnectionException, StopException, IOException {
        var r = factory.create().to(api)
                .withHeader(new RequestParameter("x-api-key", getApiKey()))
                .withHeader(RequestParameter.contentType("application/json"));
        return r.post(body);
    }

    public void reload(){
        String get = null;
        try{
            get = get("/v1/categories", null);
        }
        catch (NoConnectionException | HttpException | IOException | StopException ignored) {

        }
        if (get == null){
            categories = new ArrayList<>();
            return;
        }

        var data = gson.fromJson(get, JsonObject.class).get("data").getAsJsonArray();

        categories = data.asList().stream().map(x -> gson.fromJson(x, CurseForgeCategory.class)).toList();

    }

    public List<CurseForgeCategory> getCategories(){
        if (categories == null || categories.isEmpty())
            reload();
        return categories;
    }

    @Override
    public List<CResource> getCoreResources(List<Object> ids, Options opt) throws NoConnectionException, HttpException, StopException, IOException {
        if (ids.isEmpty())
            return null;

        var resources = getResources(ids, opt);

        if (opt.useMeta() && !opt.getIncludeDependencies())
            return resources.stream().map(x -> (CResource)CResource.fromForgeResourceGeneric(null, null, x, null)).toList();

        var loaders = opt.hasLoaderType() ? opt.getLoaders().stream().map(LoaderType::toString).toList() : null;

        var all = new ArrayList<CResource>();
        for (var x : resources){
            opt.handleId(x.id);

            try {
                fillResource(x, opt);
            } catch (NoConnectionException | HttpException ignored) {

            }

            var files = opt.doesAllowOverwrite() ? x.searchGame((List<String>) null, (List<String>) null) : x.searchGame(opt.getVersionIds(), loaders);

            if (files == null || files.isEmpty())
                continue;

            // allow overwriting for only one resource, other resources will follow the preferences
            if (opt.doesAllowOverwrite() && !x.getResourceType().isGlobal())
                opt.allowOverwrite(false);

            var f = files.get(0);

            var r = CResource.fromForgeResourceGeneric(f.mainGameVersion, f.mainLoader, x, f);
            if (r instanceof Modpack mp && opt.getAggregateModpack()){
                var manifest = getModpackManifest(mp);
                if (manifest == null) continue;

                all.addAll(getCoreResources(manifest.files.stream().map(a -> (Object) a.projectID).toList(), opt.cloneFromPlatform().meta().self(false)));
            }
            else
                all.add(r);
        }

        if (opt.getIncludeDependencies())
            all.addAll(getDependencies(all, opt.cloneFromPlatform().allowOverwrite(opt.doesAllowOverwrite()).self(false)));

        return all;
    }

    @Override
    public List<CResource> getCoreResource(Object id, Options opt) throws NoConnectionException, HttpException, StopException, IOException {
        return getCoreResources(List.of(id), opt);
    }

    @Override
    public List<CResource> getAllCoreResources(Object id, Options opt) throws NoConnectionException, HttpException, StopException, IOException {
        var res = opt.wasIdHandled(id) ? null : getResources(List.of(id), null);
        if (res == null || res.isEmpty())
            return null;
        var r = res.get(0);
        return getAllCoreResources(r, opt);
    }

    @Override
    public List<CResource> getAllCoreResources(ModResource r, Options opt) throws NoConnectionException, HttpException, IOException, StopException {
        var cfr = (CurseForgeResource) r;
        opt.handleId(cfr.id);

        fillResource(cfr, opt);

        var loaders = opt.hasLoaderType() ? opt.getLoaders().stream().map(LoaderType::toString).toList() : null;
        var files = cfr.searchGame(opt.getVersionIds(), loaders);
        return files.stream().map(a -> (CResource)CResource.fromForgeResourceGeneric(a.mainGameVersion, a.mainLoader, cfr, a)).toList();
    }

    @Override
    public List<CResource> getCoreResource(ModResource res, Options opt) throws NoConnectionException, HttpException, StopException, IOException {
        return getCoreResources(List.of(res.getId()), opt);
    }

    @Override
    public List<CResource> getDependencies(List<CResource> res, Options opt) throws NoConnectionException, HttpException, StopException, IOException {
        var mds = new ArrayList<CResource>();

        //var sendOpt = opt.getIncludeSelf() ? opt : opt.clone().includeSelf();

        for (var m : res){
            if (m.fileUrl == null)
                continue;

            if (opt.getIncludeSelf() && !opt.wasIdHandled(m.id)){
                opt.handleId(m.id);
                mds.add(m);
            }

            if (m.dependencies == null || m.dependencies.isEmpty())
                continue;

            var ms = getCoreResources(m.dependencies.stream().map(a -> a.id).filter(a -> !opt.wasIdHandled(a)).toList(), opt.dependencies(true));
            if (ms != null)
                mds.addAll(ms);
            //mds.addAll(getDependencies(ms.stream().toList(), sendOpt));
        }

        return mds;
    }

    @Override
    public Type getType() {
        return Type.CURSEFORGE;
    }

    @Override
    public <T extends Enum> Search<T> getSearch(Profile p) {
        return (Search<T>) new CurseForgeSearch(p);
    }

    @Override
    public void applyModpack(Modpack m, Path path, Options opt) throws NoConnectionException, HttpException, StopException, IOException {
        var mp = new CurseForgeModpack(m);

        var manifest = gson.fromJson(extractModpack(m, path, true, opt.getOnProgress(), opt.getCancellationToken()).read(), Manifest.class);
        mp.applyManifest(manifest);

        opt.getOnProgress().onContext(ModdingContext.RETRIEVING_MODPACK_DETAILS);

        var resources = getCoreResources(mp.getProjectIds(), Options.create(opt.getVersionId(), null).useCancellationToken(opt.getCancellationToken()).useProgressLogging(opt.getOnProgress()).meta());
        opt.getOnProgress().onContext(ModdingContext.APPLYING_MODPACK);
        mp.applyResources(resources, getFiles(mp.getFileIds()));
    }
}
